/**
 * Export utility for generating CSV and triggering downloads.
 */

export interface ExportColumn<T> {
  header: string;
  accessor: (row: T) => string | number | null | undefined;
}

/**
 * Export data as CSV and trigger browser download.
 */
export function exportToCSV<T>(
  filename: string,
  columns: ExportColumn<T>[],
  data: T[]
): void {
  const headers = columns.map((c) => `"${c.header}"`).join(',');
  const rows = data.map((row) =>
    columns
      .map((col) => {
        const val = col.accessor(row);
        if (val === null || val === undefined) return '""';
        const str = String(val).replace(/"/g, '""');
        return `"${str}"`;
      })
      .join(',')
  );

  const csvContent = [headers, ...rows].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `${filename}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Print a section of the page using a print-friendly window.
 */
export function printContent(title: string, htmlContent: string): void {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  printWindow.document.write(`
    <html>
      <head>
        <title>${title}</title>
        <style>
          body { font-family: system-ui, -apple-system, sans-serif; padding: 24px; color: #111; }
          h1 { font-size: 20px; margin-bottom: 16px; }
          table { width: 100%; border-collapse: collapse; margin-top: 16px; }
          th, td { padding: 8px 12px; border: 1px solid #ddd; text-align: left; font-size: 13px; }
          th { background: #f5f5f5; font-weight: 600; }
          tr:nth-child(even) td { background: #fafafa; }
          .footer { margin-top: 24px; font-size: 11px; color: #888; text-align: center; }
          @media print { body { padding: 0; } }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        ${htmlContent}
        <div class="footer">Generated by OmniBiz Connect on ${new Date().toLocaleDateString()}</div>
      </body>
    </html>
  `);
  printWindow.document.close();
  printWindow.print();
}

/**
 * Generate HTML table from data for printing.
 */
export function generateHTMLTable<T>(
  columns: ExportColumn<T>[],
  data: T[]
): string {
  const headers = columns.map((c) => `<th>${c.header}</th>`).join('');
  const rows = data
    .map(
      (row) =>
        '<tr>' +
        columns
          .map((col) => {
            const val = col.accessor(row);
            return `<td>${val ?? ''}</td>`;
          })
          .join('') +
        '</tr>'
    )
    .join('');

  return `<table><thead><tr>${headers}</tr></thead><tbody>${rows}</tbody></table>`;
}
