import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { CheckoutForm } from '@/components/ecommerce/CheckoutForm';
import { useCart } from '@/hooks/useCart';
import { useToast } from '@/hooks/use-toast';
import { ArrowLeft, Store, CheckCircle } from 'lucide-react';
import { Skeleton } from '@/components/ui/skeleton';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

interface StoreInfo {
  id: string;
  name: string;
  slug: string;
  logo_url?: string;
  settings?: Record<string, unknown>;
}

export default function StoreCheckout() {
  const { orgSlug } = useParams<{ orgSlug: string }>();
  const navigate = useNavigate();
  const { toast } = useToast();
  const [store, setStore] = useState<StoreInfo | null>(null);
  const [loading, setLoading] = useState(true);
  const [orderComplete, setOrderComplete] = useState(false);
  const [orderNumber, setOrderNumber] = useState<string>('');

  const cart = useCart({ organizationId: store?.id || '' });

  useEffect(() => {
    loadStore();
  }, [orgSlug]);

  const loadStore = async () => {
    if (!orgSlug) return;
    
    setLoading(true);
    try {
      const { data, error } = await supabase
        .from('organizations')
        .select('id, name, slug, logo_url, settings')
        .eq('slug', orgSlug)
        .single();

      if (error) throw error;
      setStore({
        ...data,
        name: data.name ?? '',
        slug: data.slug ?? '',
        logo_url: data.logo_url ?? undefined,
        settings: (data.settings as Record<string, unknown>) ?? undefined,
      });
    } catch (error) {
      console.error('Error loading store:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleSubmitOrder = async (formData: any, transactionReference?: string) => {
    if (!store) return;

    try {
      // Create shipping address
      const { data: addressData, error: addressError } = await supabase
        .from('shipping_addresses')
        .insert({
          organization_id: store.id,
          full_name: formData.fullName,
          email: formData.email,
          phone: formData.phone,
          address_line1: formData.addressLine1,
          address_line2: formData.addressLine2 || null,
          city: formData.city,
          state: formData.state || null,
          postal_code: formData.postalCode || null,
          country: formData.country,
        })
        .select('id')
        .single();

      if (addressError) throw addressError;

      // Calculate shipping -- rates from org settings or defaults
      const orgData = store as any;
      const orgSettings = orgData?.settings as Record<string, unknown> | undefined;
      const configuredRates = orgSettings?.shipping_rates as Record<string, number> | undefined;
      const shippingRates: Record<string, number> = configuredRates ?? {
        standard: 250,
        express: 500,
        pickup: 0,
      };
      const shippingAmount = shippingRates[formData.shippingMethod] || 0;
      const totalAmount = cart.subtotal + shippingAmount;

      // Determine payment status based on payment method and transaction reference
      const isPaystackPayment = formData.paymentMethod === 'card' || formData.paymentMethod === 'paystack';
      const paymentStatus = isPaystackPayment && transactionReference ? 'paid' : 'pending';

      // Create order
      const { data: orderData, error: orderError } = await supabase
        .from('online_orders')
        .insert({
          organization_id: store.id,
          shipping_address_id: addressData.id,
          order_number: '', // Will be auto-generated by trigger
          subtotal: cart.subtotal,
          shipping_amount: shippingAmount,
          total_amount: totalAmount,
          payment_method: formData.paymentMethod,
          payment_reference: transactionReference || null,
          shipping_method: formData.shippingMethod,
          status: 'pending',
          payment_status: paymentStatus,
        })
        .select('id, order_number')
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = cart.items.map((item) => ({
        order_id: orderData.id,
        product_id: item.product_id,
        variant_id: item.variant_id || null,
        product_name: item.product_name,
        variant_name: item.variant_name || null,
        quantity: item.quantity,
        unit_price: item.unit_price,
        total_price: item.unit_price * item.quantity,
      }));

      const { error: itemsError } = await supabase
        .from('online_order_items')
        .insert(orderItems);

      if (itemsError) throw itemsError;

      // Clear cart
      await cart.clearCart();

      // Show success
      setOrderNumber(orderData.order_number);
      setOrderComplete(true);

      toast({
        title: 'Order placed successfully!',
        description: `Your order number is ${orderData.order_number}`,
      });
    } catch (error) {
      console.error('Error creating order:', error);
      toast({
        title: 'Order failed',
        description: 'There was an error processing your order. Please try again.',
        variant: 'destructive',
      });
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-background">
        <div className="border-b">
          <div className="container mx-auto flex h-16 items-center px-4">
            <Skeleton className="h-8 w-48" />
          </div>
        </div>
        <div className="container mx-auto px-4 py-8">
          <Skeleton className="mb-8 h-10 w-64" />
          <div className="grid gap-8 lg:grid-cols-2">
            <div className="space-y-4">
              <Skeleton className="h-48 w-full" />
              <Skeleton className="h-48 w-full" />
            </div>
            <Skeleton className="h-96 w-full" />
          </div>
        </div>
      </div>
    );
  }

  if (orderComplete) {
    return (
      <div className="min-h-screen bg-background">
        <header className="border-b">
          <div className="container mx-auto flex h-16 items-center gap-3 px-4">
            {store?.logo_url ? (
              <img src={store.logo_url} alt={store.name} className="h-8 w-8 rounded-lg object-cover" />
            ) : (
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary">
                <Store className="h-5 w-5 text-primary-foreground" />
              </div>
            )}
            <h1 className="text-xl font-bold">{store?.name}</h1>
          </div>
        </header>

        <main className="container mx-auto flex min-h-[calc(100vh-4rem)] items-center justify-center px-4 py-8">
          <Card className="w-full max-w-md text-center">
            <CardHeader>
              <div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-green-100">
                <CheckCircle className="h-10 w-10 text-green-600" />
              </div>
              <CardTitle className="text-2xl">Order Confirmed!</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <p className="text-muted-foreground">
                Thank you for your order. We've received your order and will begin processing it shortly.
              </p>
              <div className="rounded-lg bg-muted p-4">
                <p className="text-sm text-muted-foreground">Order Number</p>
                <p className="text-lg font-bold">{orderNumber}</p>
              </div>
              <p className="text-sm text-muted-foreground">
                A confirmation email will be sent to your email address.
              </p>
              <div className="flex flex-col gap-2 pt-4">
                <Button onClick={() => navigate(`/store/${orgSlug}`)}>
                  Continue Shopping
                </Button>
              </div>
            </CardContent>
          </Card>
        </main>
      </div>
    );
  }

  if (cart.items.length === 0 && !loading) {
    return (
      <div className="min-h-screen bg-background">
        <header className="border-b">
          <div className="container mx-auto flex h-16 items-center gap-3 px-4">
            <Button variant="ghost" size="icon" onClick={() => navigate(`/store/${orgSlug}`)}>
              <ArrowLeft className="h-5 w-5" />
            </Button>
            <h1 className="text-xl font-bold">{store?.name}</h1>
          </div>
        </header>
        <main className="container mx-auto flex min-h-[calc(100vh-4rem)] items-center justify-center px-4">
          <div className="text-center">
            <h2 className="text-xl font-semibold">Your cart is empty</h2>
            <p className="mt-2 text-muted-foreground">Add some products before checking out.</p>
            <Button className="mt-4" onClick={() => navigate(`/store/${orgSlug}`)}>
              Browse Products
            </Button>
          </div>
        </main>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b">
        <div className="container mx-auto flex h-16 items-center gap-3 px-4">
          <Button variant="ghost" size="icon" onClick={() => navigate(`/store/${orgSlug}`)}>
            <ArrowLeft className="h-5 w-5" />
          </Button>
          {store?.logo_url ? (
            <img src={store.logo_url} alt={store?.name} className="h-8 w-8 rounded-lg object-cover" />
          ) : (
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary">
              <Store className="h-5 w-5 text-primary-foreground" />
            </div>
          )}
          <h1 className="text-xl font-bold">{store?.name}</h1>
        </div>
      </header>

      {/* Main Content */}
      <main className="container mx-auto px-4 py-8">
        <div className="mb-8">
          <h2 className="text-3xl font-bold tracking-tight">Checkout</h2>
          <p className="mt-2 text-muted-foreground">
            Complete your order by filling in your details below
          </p>
        </div>

        <CheckoutForm
          items={cart.items}
          subtotal={cart.subtotal}
          onSubmit={handleSubmitOrder}
          onCancel={() => navigate(`/store/${orgSlug}`)}
          paystackPublicKey={
            (store?.settings as Record<string, unknown>)?.paystack_public_key as string | undefined ||
            import.meta.env.VITE_PAYSTACK_PUBLIC_KEY ||
            'pk_test_xxxxxxxxxxxxx'
          }
        />
      </main>
    </div>
  );
}
